source 'https://github.com/CocoaPods/Specs.git'

target "SoundRecognizer" do
    platform :ios, '13.0'
    use_frameworks!
    inhibit_all_warnings!
	
    pod 'RosaKit', :path => '../../'
    pod 'ZIPFoundation'

end

target "SoundRecognizerTests" do
    platform :ios, '13.0'
    use_frameworks!
    inhibit_all_warnings!
  
    pod 'RosaKit', :path => '../../'

end
